---
- name: Manage configuration.yaml
  hosts: aws
  remote_user: ansible-test
  tasks:
    - name: Ensure configuration.yaml exists
      ansible.builtin.file:
        path: ./configuration.yaml
        state: touch

    - name: Set fact with combined values
      ansible.builtin.set_fact:
        combined_line: "apple, orange, banana, mango, grape"

    - name: Insert combined values into configuration.yaml
      ansible.builtin.lineinfile:
        path: ./configuration.yaml
        line: "{{ combined_line }}"
        create: yes

    - name: Display the contents of configuration.yaml
      ansible.builtin.slurp:
        src: ./configuration.yaml
      register: file_contents

    - ansible.builtin.debug:
        msg: "{{ file_contents['content'] | b64decode }}"

    - name: Modify 'banana' to 'avocado' and 'grape' to 'watermelon'
      ansible.builtin.replace:
        path: ./configuration.yaml
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - { regexp: 'banana', replace: 'avocado' }
        - { regexp: 'grape', replace: 'watermelon' }

    - name: Display the contents of configuration.yaml after modification
      ansible.builtin.slurp:
        src: ./configuration.yaml
      register: modified_file_contents

    - ansible.builtin.debug:
        msg: "{{ modified_file_contents['content'] | b64decode }}"
