---
- name: Setup ansible-test user on EC2
  hosts: aws
  become: true
  remote_user: ubuntu
  vars:
    user: ansible-test
  tasks:
    - name: Ensure the ansible-test user exists
      user:
        name: "{{ user }}"
        state: present
        create_home: yes

    - name: Create .ssh directory for ansible-test
      file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0700'

    - name: Copy SSH authorized_keys file
      command: >
        cp /home/ubuntu/.ssh/authorized_keys /home/{{ user }}/.ssh/authorized_keys
      args:
        creates: /home/{{ user }}/.ssh/authorized_keys

    - name: Ensure ownership and permissions of authorized_keys
      file:
        path: "/home/{{ user }}/.ssh/authorized_keys"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0600'

    - name: Allow ansible-test user to run sudo without a password
      copy:
        content: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/{{ user }}"
        owner: root
        group: root
        mode: '0440'
